version: "3.2"

services:

  php:
    restart: always
    build:
      context: ./docker
      args:
        USER_NAME: ${D_PROJECT_NAME}_php
        USER_ID: ${D_USER_ID}
        VERSION: ${PHP_VERSION}-apache
        PHP_VERSION: ${PHP_VERSION}
    userns_mode: "host"
    container_name: ${D_PROJECT_NAME}_php
    user: "${D_USER_ID}:${D_GROUP_ID}"
    ports:
      - 80:80
    links:
      - db
    volumes:
      - ./docker/PHP/docker-php.ini:/usr/local/etc/php/conf.d/php.ini
      - ${D_SOURCE_DIR}:/var/www/html
      - .composer:/home/${D_PROJECT_NAME}_php/.composer
      - ./logs/error.log:/var/log/apache2/error.log
      - ./logs/access.log:/var/log/apache2/access.log

  mailhog:
    restart: always
    container_name: ${D_PROJECT_NAME}_mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  db:
    restart: always
    image: mysql:5.6
    userns_mode: "host"
    container_name: ${D_PROJECT_NAME}_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306
    volumes:
      - ${D_MYSQL_DATA_DIR}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TERM=meh

  phpmyadmin:
    restart: always
    container_name: ${D_PROJECT_NAME}_pma
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 81:80
    environment:
      - PMA_USER=devdb
      - PMA_PASSWORD=devdb